### ISSUE TITLE
Leaves drop and finite water issue

### ISSUE THREAD

**Issue by zHawky** [quentin452/tropicraft-REUP#1]
When breaking a tropicraft leaves block, like fruit leaves or rainforest leaves, birch saplings are dropped, rather than saplings of the actual tropicraft tree. This is a fix for that and allows tropics water to become an infinite water source, like vanilla water.

https://github.com/Tropicraft/Tropicraft/pull/106
https://github.com/Tropicraft/Tropicraft/pull/105

**Comment by quentin452** [comment]
these PRs are for a newer version of tropicraft(minecraft) right?

**Comment by zHawky** [comment]
> these PRs are for a newer version of tropicraft(minecraft) right?

yep
